- name: Add Firewalld port rules
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ zk_client_port }}/tcp"
    - "{{ zk_leader_port }}/tcp"
    - "{{zk_port }}/tcp"
