---
- name: Add ZooKeeper rules to iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{item}} -j ACCEPT -m comment --comment "ZooKeeper"
  with_items:
       - "{{ zk_client_port }}"
       - "{{ zk_leader_port }}"
       - "{{ zk_port }}"
  notify: Save iptables
  tags: network
