- name: reload systemctl daemon
  command: systemctl daemon-reload

- name: Restart zookeeper
  service: name=zookeeper state=restarted

- name: Save iptables
  command: "iptables-save > /etc/sysconfig/iptables"
